logging:
  level:
    root: info

spring:
  config:
    import: "classpath:application.yml"

confluence:
  cert-name: "" #Имя сертификата с которым ходишь в конфлюенс
  confluence-url: "" #базовый адрес конфлюенса
  confluence-space-key: "" #Спейс кей пространства в конфлюенсе
  confluence-parent-page-id: "" # 2154245320
  
#influx-db:
#  influxdb-url: "http://anketa-infra-lt:8086" #Базовый урл до тачки с инфлюксом
#  database-name: gatling #Название базы где лежат метрики gatling/anketa

vm:
  vm-url: ""

jira:
  task-id: LOADTEST-23144 #ID задачи на тестирование в Jira
  task-title: ДК НТ нового сервиса dc-log-masker #Название задачи
  
utility:
  results-folder: results #Папка куда будут складываться результаты
  load-station: gatling #Выбор инструмента нагрузки. Возможные значения: gatling/PC
  graphs-needed: false #флаг нужно выгружать графики или нет (при обновлении страницы)

infrastructure:
  components:
    kubernetes-worker:
      configuration:
        cpu: 4
        ram: 8
        nodesCount: 4
    redis:
      configuration:
       cpu: 4
       ram: 8
       nodesCount: 3
    postgres:
      configuration:
        cpu: 4
        ram: 8
        nodesCount: 3
    kafka:
      configuration:
        cpu: 1
        ram: 4
        nodesCount: 3

test-configuration:
  max-performance:
    enable: false #Флаг что нужно выгружать этот тест. true/false
    test-end-time: "2025-05-21 10:51:45"
    #Чтобы посчитать ступени в калькуляторе приходится узнавать время начала теста
    test-start-time: "2025-05-21 10:51:45"
    load-level: 300 #Стартовый уровень нагрузки (первой ступени)
    step-duration: 30 #Длительность полки В МИНУТАХ
    #Для калькулятора. ВСЕ В МИНУТАХ
    steps-count: 10  #количество шагов
    ramp-time: 30 #Длительность первого разгона//длительность полки
    separating-ramp: 10 #Длительность рампы между ступенями
    step-percent: 20 #Шаг роста нагрузки. Проценты
    stabilization-time: 5 #Время на стабилизацию нагрузки. Лишнее время у ступени
  confirm-max:
    enable: false #Флаг что нужно выгружать этот тест. true/false
    test-end-time: "2025-04-25 13:49:52" #2025-04-23 11:24:14
    test-duration: 135 #Длительность всего теста. Рампа + ступень
    load-level: 410 #Уровень нагрузки
    step-duration: 60 #Длительность полки
  reliability:
    enable: true #Флаг что нужно выгружать этот тест. true/false
    test-end-time: "2025-05-21 10:51:45"
    load-level: 100 #Уровень нагрузки
    step-duration: 45 #Длительность полки

performance-center:
  pc-url: ""
  pc-domain: 
  pc-project: 

grafana:
  grafana-url: "" #Адрес графаны
  grafana-api-key: "" #API ключ для авторизации
  grafana-width: 1000 #Ширина графика
  grafana-height: 500 #Высота
  prometheus-url: ""
  enviroment: kubernetes #либо kubernetes либо mesos. Флаг чем вы пользуетесь
  kubernetes:
    namespace-name: "load" #Неймспейс в котором лежит деплоймент

  groups:
    grafanaGroups:
      - title: ""
        dashboardName: ""
        dashboardUUID: ""
        panels:
          - 1221
          - 1223
          - 1225
        applications: ""
      - title: ""
        dashboardName: ""
        dashboardUUID: ""
        panels:
          - 944
          - 939
          - 959
        applications: ""
        variables:
          kafka-topic:
            - ""
            - ""
      - title: ""
        dashboardName: ""
        dashboardUUID: ""
        panels:
          - 898
          - 899
          - 902
        variables:
        applications:
          - ""
          - ""
      - title: ""
        dashboardName: ""
        dashboardUUID: ""
        panels:
          - 900
          - 901
          - 909
          - 907
          - 904
          - 917
          - 932
          - 931
          - 920
          - 923
          - 976
        variables:
        applications:
          - ""
          - ""
        needPod: true #Флаг надо выгружать график отдельно для пода/инстанса или нет

      - title: ""
        dashboardName: ""
        dashboardUUID: ""
        panels:
          - 24
          - 33
          - 7
          - 25
          - 1
          - 16
          - 13
          - 14
        variables:
        applications:
          - ""
          - ""
          - ""
      - title: ""
        dashboardName: ""
        dashboardUUID: ""
        panels:
          - 77
          - 78
          - 74
          - 152
        variables:
        applications:
          - ""
          - ""
          - ""


fault-tolerance:
  enable: false
  test-end-time: ""
  load-level: ""

  stages:
    - fault-scenario-test-name: ""
      fault-scenario-test-end: ""
      fault-scenario-test-length: ""
      fault-scenario-stabilization-length: ""