logging:
  level:
    root: info

spring:
  config:
    import: "classpath:application.yml"

confluence:
  cert-name: "" #Имя сертификата с которым ходишь в конфлюенс
  confluence-url: "" #базовый адрес конфлюенса
  confluence-space-key: "" #Спейс кей пространства в конфлюенсе
  confluence-parent-page-id: "" # 2154245320
  
#influx-db:
#  influxdb-url: "" #Базовый урл до тачки с инфлюксом
#  database-name: gatling #Название базы где лежат метрики gatling/anketa

vm:
  vm-url: ""

jira:
  task-id: #ID задачи на тестирование в Jira
  task-title:  #Название задачи
  
utility:
  results-folder: results #Папка куда будут складываться результаты
  load-station: gatling #Выбор инструмента нагрузки. Возможные значения: gatling/PC
  graphs-needed: true #флаг нужно выгружать графики или нет (при обновлении страницы)

infrastructure:
  components:
    kubernetes-worker:
      configuration:
        cpu: 12
        ram: 64
        nodesCount: 4
    redis:
      configuration:
       cpu: 1
       ram: 1
       nodesCount: 3
    postgres:
      configuration:
        cpu: 12
        ram: 32
        nodesCount: 3
    kafka:
      configuration:
        cpu: 1
        ram: 4
        nodesCount: 3

test-list:
  testList:
    - testType: "Тест надежности"
      testEndTime: "2025-06-04 14:26:01"
      loadLevel: 100 #Уровень нагрузки
      stepDuration: 120 #Длительность полки

performance-center:
  pc-url: ""
  pc-domain: LT
  pc-project:

grafana:
  grafana-url: "" #Адрес графаны
  grafana-api-key: "" #API ключ для авторизации
  grafana-width: 1000 #Ширина графика
  grafana-height: 500 #Высота
  prometheus-url: ""
  environment: kubernetes #либо kubernetes либо mesos. Флаг чем вы пользуетесь
  kubernetes:
    namespace-name: "" #Неймспейс в котором лежит деплоймент

  groups:
    grafanaGroups:
      - title: ""
        dashboardName: ""
        dashboardUUID: ""
        panels:
          - 3
          - 1
          - 2
          - 475
        applications: ""
      - title: ""
        dashboardName: ""
        dashboardUUID: ""
        panels:
          - 944
          - 939
          - 959
        applications: ""
      - title: ""
        dashboardName: ""
        dashboardUUID: ""
        panels:
          - 898
          - 899
          - 902
        applications:
          - ""
          - ""



fault-tolerance:
  enable: false
  test-end-time: "2025-01-14 17:03:13"
  load-level: "100"

  stages:
    - fault-scenario-test-name: "/logistics-api"
      fault-scenario-test-end: "2025-02-04 16:15:01"
      fault-scenario-test-length: "15"
      fault-scenario-stabilization-length: "15"